easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Project
        - App\Entity\Context
        - App\Entity\Techno
        - App\Entity\Image
        - App\Entity\Contact

    list:
        fields:
            - { property: 'image', type: 'image', base_path: '%app.path.products_images%' }
