vich_uploader:
     db_driver: orm

     mappings:
        products_image:
            uri_prefix: /uploads/images/projets
            upload_destination: '%kernel.project_dir%/public/uploads/images/projets'
