<?php

namespace ContainerEaHBzlg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ik_3A5t.App\Entity\Project' shared service.
     *
     * @return \App\Entity\Project
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ik_3A5t": it references class "App\\Entity\\Project" but no such service exists.');
    }
}
